import {
  Sparkles,
  LayoutDashboard,
  TrendingUp,
  CalendarDays,
  Plus,
  Users,
  BarChart3,
  HelpCircle,
} from 'lucide-react'
import type { TourDefinition } from '../types'

export const generalTour: TourDefinition = {
  id: 'general',
  title: 'Tour General',
  description: 'Conoce las funciones principales del sistema en 7 pasos',
  localStorageKey: 'courtops_tour_general_v1',
  steps: [
    {
      id: 'welcome',
      target: null,
      icon: Sparkles,
      title: '¡Bienvenido a CourtOps!',
      description:
        'Tu club ya está configurado. En los próximos minutos vas a conocer todo lo que necesitás para operar de manera profesional.',
      position: 'center',
    },
    {
      id: 'sidebar-nav',
      target: '[data-tour="sidebar-nav"]',
      category: 'Navegación',
      icon: LayoutDashboard,
      title: 'Tu centro de control',
      description:
        'El menú lateral es tu punto de partida. Desde acá accedés a Reservas, Clientes, Kiosco, Caja, Reportes y Configuración con un solo clic.',
      proTip: 'En pantallas pequeñas el menú colapsa a íconos para maximizar el espacio. Pasá el cursor para ver las etiquetas.',
      position: 'right',
      padding: 8,
      borderRadius: 16,
      waitForElement: true,
    },
    {
      id: 'dashboard-stats',
      target: '[data-tour="dashboard-stats"]',
      category: 'Métricas',
      icon: TrendingUp,
      title: 'Pulso de tu negocio',
      description:
        'Ingresos del día, reservas activas, deudas pendientes y ocupación de canchas. Todos los números clave en tiempo real, sin reportes manuales.',
      proTip: 'Hacé clic en cualquier métrica para ver el detalle. Los datos se actualizan automáticamente cada vez que se registra una acción.',
      position: 'bottom',
      padding: 8,
      borderRadius: 20,
      waitForElement: true,
    },
    {
      id: 'turnero-grid',
      target: '[data-tour="turnero-grid"]',
      category: 'Reservas',
      icon: CalendarDays,
      title: 'La grilla de canchas',
      description:
        'El corazón del sistema. Cada columna es una cancha, cada fila es un horario. Los colores indican el estado de pago: verde (pagado), amarillo (señado), rojo (deuda).',
      proTip: 'Hacé clic en cualquier espacio vacío para crear una reserva ahí mismo, sin necesidad de completar formularios adicionales.',
      position: 'top',
      padding: 6,
      borderRadius: 24,
      waitForElement: true,
      scrollIntoView: true,
    },
    {
      id: 'new-booking',
      target: '[data-tour="new-booking-btn"]',
      category: 'Acción rápida',
      icon: Plus,
      title: 'Nueva reserva en segundos',
      description:
        'Creá una reserva eligiendo cancha, horario y cliente. Podés cobrar en el momento o dejar deuda pendiente. Todo queda registrado automáticamente.',
      proTip: 'Atajo de teclado: presioná "N" desde cualquier parte del dashboard para abrir el modal de nueva reserva al instante.',
      position: 'bottom',
      padding: 8,
      borderRadius: 14,
      waitForElement: true,
    },
    {
      id: 'nav-clientes',
      target: '[data-tour="nav-clientes"]',
      category: 'Clientes',
      icon: Users,
      title: 'Ficha completa por jugador',
      description:
        'Historial de turnos, deudas, membresías activas y waivers firmados digitalmente. Todo centralizado. Nunca más "¿cuándo jugó este cliente?".',
      proTip: 'Los clientes se crean automáticamente cuando hacen una reserva online desde tu link público. No necesitás cargarlos a mano.',
      position: 'right',
      padding: 6,
      borderRadius: 12,
      waitForElement: true,
    },
    {
      id: 'nav-reportes',
      target: '[data-tour="nav-reportes"]',
      category: 'Analytics',
      icon: BarChart3,
      title: 'Decisiones basadas en datos',
      description:
        'Ingresos por día y semana, ocupación por cancha, productos más vendidos, horas pico. Todo exportable a Excel para tu contador.',
      proTip: 'Usá el reporte de ocupación para detectar horarios flojos y hacer promociones dirigidas. Es la herramienta más subestimada del sistema.',
      position: 'right',
      padding: 6,
      borderRadius: 12,
      waitForElement: true,
    },
    {
      id: 'finish',
      target: null,
      icon: HelpCircle,
      title: '¡Ya estás listo para operar!',
      description:
        'Exploraste las funciones clave de CourtOps. Si necesitás profundizar en Kiosco, Reservas, Clientes o Reportes, tenés tours específicos disponibles.',
      position: 'center',
    },
  ],
}
